version: '3.3'

services:
  php-srv:
    image: php:8.2-apache
    container_name: server1
    ports:
      - "8000:80"
    volumes:
      - ./Site:/var/www/html
    build:
      context: .
      dockerfile: Dockerfile
    networks:
      - network

  db-srv:
    image: mysql:8.0
    container_name: server
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: database
      MYSQL_USER: Louis
      MYSQL_PASSWORD: pass
    ports:
      - "3333:3306"
    networks:
      - network
networks:
  network:
    driver: bridge
